# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('photologue_custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGallery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('photologue.gallery',),
        ),
    ]
